In [9]:
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
DF = pd.read_csv("keystroke.csv",header=None)


C:\Users\mohan\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [10]:
DF.columns = DF.iloc[0]
DF=DF.drop([0], axis=0)
DF=DF.drop(['sessionIndex', 'rep'], axis=1)
print(DF)

0     subject H.period DD.period.t UD.period.t     H.t  DD.t.i  UD.t.i  \
1        s002   0.1491      0.3979      0.2488  0.1069  0.1674  0.0605   
2        s002   0.1111      0.3451       0.234  0.0694  0.1283  0.0589   
3        s002   0.1328      0.2072      0.0744  0.0731  0.1291   0.056   
4        s002   0.1291      0.2515      0.1224  0.1059  0.2495  0.1436   
5        s002   0.1249      0.2317      0.1068  0.0895  0.1676  0.0781   
...       ...      ...         ...         ...     ...     ...     ...   
20396    s057   0.0884      0.0685     -0.0199  0.1095   0.129  0.0195   
20397    s057   0.0655       0.063     -0.0025   0.091  0.1148  0.0238   
20398    s057   0.0939      0.1189       0.025  0.1008  0.1122  0.0114   
20399    s057   0.0923      0.1294      0.0371  0.0913   0.099  0.0077   
20400    s057   0.0596       0.131      0.0714  0.0992  0.1103  0.0111   

0         H.i  DD.i.e  UD.i.e  ...     H.a  DD.a.n  UD.a.n     H.n  DD.n.l  \
1      0.1169  0.2212  0.1043  ..

In [11]:
#Random Forest 
X4=DF.iloc[:,1:32].values
Y4=DF.iloc[:,0].values.reshape(-1, 1)
X_train, X_test, y_train, y_test = train_test_split(X4, Y4, random_state = 0) 
  
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=200)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

C:\Users\mohan\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  if sys.path[0] == '':


In [12]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
from sklearn.metrics import confusion_matrix

conf_mat = confusion_matrix(y_test, y_pred)
print(conf_mat)

Accuracy: 0.9396078431372549
[[ 78   1   0 ...   0   0   0]
 [  0  89   3 ...   0   0   0]
 [  2   1  82 ...   0   0   0]
 ...
 [  1   0   0 ... 102   2   0]
 [  0   0   1 ...   0  83   0]
 [  0   0   0 ...   1   0  72]]
